config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create, :destroy]

  resources :days, only: [:index, :show, :create, :new, :update] do
    resources :votes, only: [:create]
    resources :pitches, only: [:create]
  end

  resources :pitches, only: [:create, :new] do
    resources :votes, only: [:create]
  end

  resources :admins, only: [:new, :create]

  get 'teams/new' => 'users#edit'
  post 'teams' => 'users#patch'

end

app/models/day.rb
class Day < ApplicationRecord
  has_many :pitches
  has_many :rounds
  has_many :votes, through: :rounds
  
  validates :cohort_name, :pic_url, :round_status, :date, :passing_number, :teams_total, presence: true
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
	before_action :require_login

  def new
		redirect_to days_path unless admin?
	end

  def index
    @days = Day.all
  end

  def show
    @users = User.all
    @pitch = Pitch.new()
    @day = Day.find_by(id: params[:id])
    @pitches = Pitch.all.where(day_id: @day.id)
  end

  def create
  	redirect_to days_path unless admin?

  	day = Day.new(days_params)
  	if day.save
  		redirect_to days_path
  	else
  		@errors = day.errors.full_messages
  		render new_day_path
  	end
  end

  def update
  	day = Day.find_by(id: params[:id])

  	day.round_status = advance_to_next_round(day)
  	day.save
    if day.round_status == 'closed'
      @users = User.all
      p "---------------------------------------------"
      p @users
      @pitches = day.pitches
      render teams_new_path
    else
      redirect_to days_path
    end
  end

  private
	def days_params
		params.require(:day).permit(:cohort_name, :pic_url, :round_status, :date, :passing_number, :teams_total)
	end

end

app/helpers/days_helper.rb
module DaysHelper

end

app/views/days/days.html.erb
<h1>Test</h1>

app/views/days/index.html.erb
<h1>Past to Present Pitch Days</h1>
<% if admin? %>
	<%= link_to "Add a new day", new_day_path, class: "waves-effect waves-teal btn-flat" %>
<% end %>

<% @days.each do |day| %>
    <div class="row proj">
      <div class="col s12">
        <div class="col s8 offset-s2">
          <div class="card medium">
            <div class="card-image">
              <img src="<%=	day.pic_url %>">
              <span class="card-title"><%= day.cohort_name %></span>
            </div>
            <div class="card-content">
              <p>
                <span><%= day.date %></span><br>
                <span><%= day.round_status %></span>
              </p>
            </div>
            <div class="card-action">
              <%= link_to 'Go to Day', day_path(day) %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/days/new.html.erb
<h1>Add Another Day</h1>

  <div class="row">
  	 <% if @errors %>
        <ul>
          <% @errors.each do |error| %>
              <li><%= error %></li>
          <% end %>
        </ul>
    <% end %>
      <div class="card-panel">
        <%= form_for :day, class: 'col s12', url: '/days' do |f| %>
            <div class="row">
              <div class="input-field col s6">
                <%= f.text_field :cohort_name,class: 'validate' %><br>
                <%= f.label :cohort_name %>
              </div>
              <div class="input-field col s6">
                <%= f.url_field :pic_url, class: 'validate' %><br>
                <%= f.label :pic_url %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :round_status, class: 'validate' %>
                <%= f.label :round_status %><br>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.number_field :passing_number, class: 'validate' %>
                <%= f.label :passing_number %><br>
              </div>
            </div>
             <div class="row">
              <div class="input-field col s12">
                <%= f.number_field :teams_total, class: 'validate' %>
                <%= f.label :teams_total %><br>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.date_field :date, class: 'datepicker' %>
                <%= f.label :date %><br>
              </div>
            </div>
            <div class="row">
              <%= f.submit 'Register', class: 'btn waves-effect waves-light right' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/days/show.html.erb
<% if admin? && @day.round_status != "closed" %>
  <%= form_for :day, url: day_path(@day.id), method: :patch do |f|%>
    <%= f.submit "Advance to next round", class: "waves-effect waves-teal btn-flat" %>
  <% end %>
<% end %>

<div class="row">
  <div class="col s12 center-align">
    <% if @pitches.empty? %>
        <h3>Please add a pitch</h3>

    <% elsif @day.round_status == 'open' %>
        <div class="row">
          <div class="col s12">
            <ul class="pitch-list">
              <% @pitches.each do |pitch| %>
                <%= render partial: '/pitches/pitch', locals: {pitch: pitch} %>
              <% end %>
            </ul>
          </div>
        </div>


    <% elsif @day.round_status == 'round_1' %>
      <ul class="pitch-list">

        <% @pitches.each do |pitch| %>
            <%= render partial: '/pitches/pitch', locals: {pitch: pitch} %>


        <form class="vote-form" action="<%= day_votes_path(@day) %>" method="POST">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
            <li>
              <span>- Rank -</span><br>
              <% if voted?(@day, 1) %>
                <span>Thanks for Voting Friend!</span>
              <% else %>
                <% @pitches.count.times do |i| %>
                  <span>
                    <input name="row-<%= pitch.id %>" type="radio" value="<%= i %>" id="<%= pitch.id %>-<%= i %>" data-col="<%= i %>" />
                    <label for="<%= pitch.id %>-<%= i %>"> <%= i + 1 %> </label>
                  </span>
                <% end %>
              <% end %>
            </li>
        <% end %>
        <input class="mass-submit waves-effect waves-light btn" type="submit" value="Submit Votes">
        </form>
      </ul>

    <% elsif @day.round_status == 'round_2' %>
      <% winners = round_1_winners(@pitches, @day) %>
      <ul class="pitch-list">
        <form class="vote-form" action="<%= day_votes_path(@day) %>" method="POST">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        <% winners.each do |pitch| %>
            <%= render partial: '/pitches/pitch', locals: {pitch: pitch} %>
            <li>
              <span>- Rank -</span><br>
              <% if voted?(@day, 2) %>
                <span>Thanks for Voting Friend!</span>
              <% else %>
                <% winners.count.times do |i| %>
                  <span>
                    <input name="row-<%= pitch.id %>" type="radio" value="<%= i %>" id="<%= pitch.id %>-<%= i %>" data-col="<%= i %>" />
                    <label for="<%= pitch.id %>-<%= i %>"> <%= i + 1 %> </label>
                  </span>
                <% end %>
              <% end %>
            </li>
        <% end %>
        <input class="mass-submit waves-effect waves-light btn"type="submit" value="Submit Votes">
        </form>
      </ul>

    <% else %>
        <% champs = round_2_winners(round_1_winners(@pitches, @day), @day) %>
          <ul>
            <% champs.each do |pitch| %>
                <%= render partial: '/pitches/pitch', locals: {pitch: pitch} %>
                <li>
                  <span>- Rank -</span><br>
                </li>
            <% end %>
          </ul>
      <% end %>

    <% if @day.round_status == 'open' %>
      <div class="row">
        <div class="center-align">
          <a class="waves-effect waves-light btn-large center" id="show_pitch_form_button">Make a Pitch</a>
        </div>
      </div>
      <div class="row">
        <div class="center-align">
            <%= render partial: '/pitches/add_pitch', locals: {day: @day, pitch: @pitch} %>
        </div>
      </div>
    <% end %>
  </div>
</div>