config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#new'
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:create, :destroy]

  resources :days, only: [:index, :show, :create, :new, :update] do
    resources :votes, only: [:create]
    resources :pitches, only: [:create]
  end

  resources :pitches, only: [:create, :new] do
    resources :votes, only: [:create]
  end

  resources :admins, only: [:new, :create]

  get 'teams/new' => 'users#edit'
  post 'teams' => 'users#patch'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PitchPerfect</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <nav>
        <div class="nav-wrapper">
          <% if logged_in? %>
            <%= link_to 'PitchPerfect', days_path, class: 'brand-logo' %>
          <% else %>
            <%= link_to 'PitchPerfect', root_path, class: 'brand-logo' %>
          <% end %>
          <ul id="nav-mobile" class="right">
            <% if logged_in? %>
            <li><%= link_to 'home', days_path %></li>
              <li><%= link_to 'logout', session_path(current_user), method: :delete %></li>
                <% if admin? %>
                  <li><%= link_to 'add admin', new_admin_path %></li>
                <% end %>
            <% else %>
              <li><%= link_to 'home', root_path %></li>
              <li><%= link_to 'login', root_path %></li>
              <li><%= link_to 'register', root_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>

      <%= yield %>

    </div>
  </body>
</html>